-- This file is an informational snapshot of an older schema and is intentionally
-- non-executable. It used to include raw CREATE statements and comment markers
-- that confused the SQL migrator. To avoid parsing errors, the content was
-- removed and replaced with this short explanatory note.
-- If you need to apply any statements from the old snapshot, copy them into
-- a new migration file with proper SQL formatting.